# Aaron Rodriguez Assigment-11

## Requirement 1

In [88]:
# Describe the commonalities and differences between
# NumPy arrays and Pandas series



# Pandas module works more with tabular data whereas the Numpy module work with numerical data
# Numpy library provides objects for multi-dimensional arrays, whereas Pandas is caple of offfering and in-memory 2D table object called DataFram
# Common - hey both provide powerful tools, and although they are different types of data they both work it data.

## Requirement 2

In [89]:
import numpy as np
import pandas as pd

In [90]:
#  Create a Pandas series named bill_names with American currency bill 
# denominations as indices (keys) and President last names as values.
bill_names = {'Washington': 1,
              'Jefferson': 2,
              'Lincon': 5,
              'Jackson': 10,
              'Grant': 50}
bill_names = pd.Series(bill_names)
bill_names

Washington     1
Jefferson      2
Lincon         5
Jackson       10
Grant         50
dtype: int64

### Requirement 2

In [91]:
# Create a Pandas series-as-dictionary beverages_dict.
# • individual values via the keys
beverages_dict = {'Coke': 'Taste like battery acid',
                 'Dr.Pepper':'Is the most refreshing drink ever!',
                 'Big Red': 'This drink must be had with BBQ!!',
                 'Sprite': 'The best drink to have with a sanwhich!',
                 'Root Beer': 'One of the best creations ever!'}
soda = pd.Series(beverages_dict)
soda['Dr.Pepper']

'Is the most refreshing drink ever!'

In [92]:
# • multiple values via slicing
soda[2:5]

Big Red            This drink must be had with BBQ!!
Sprite       The best drink to have with a sanwhich!
Root Beer            One of the best creations ever!
dtype: object

### Requirement 3

In [93]:
# Obtain the real city proper population data for the following cities:
# Create a series-as-dictionary named population based on this information
import numpy as np
import pandas as pd

In [94]:
population = {'Chongquing': 31020000,
              'Shanghai': 2632000,
              'Tokyo': 139600000,
              'Moscow': 12593252,
              'Mexico City': 21918936,
              'London': 9425622,
              'New York': 20174987}
pop = pd.Series(population)
pop

Chongquing      31020000
Shanghai         2632000
Tokyo          139600000
Moscow          12593252
Mexico City     21918936
London           9425622
New York        20174987
dtype: int64

### Requirement 4

In [95]:
# Create a Pandas series-as-dictionary named city_country with the cities in 
# population and the countries for each city.

city_country = {'Chongquing': 'China',
                'Shanghai': 'China',
                'Tokyo': 'Japan',
                'Moscow': 'Russia',
                'Mexico City': 'Mexico',
                'London': 'England',
                'New York': 'America'}
city = pd.Series(city_country)
city

Chongquing       China
Shanghai         China
Tokyo            Japan
Moscow          Russia
Mexico City     Mexico
London         England
New York       America
dtype: object

#

In [96]:
# Create a Pandas dataframe object named city_dataframe from a dictionary 
# of series objects using population and city_country

#the .index property
print(city.index)
print(pop.index)

Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')
Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')


In [97]:
# The .columns property
city_dataframe = pd.DataFrame({'population': pop,
                              'country': city})
city_dataframe

population  country
Chongquing     31020000    China
Shanghai        2632000    China
Tokyo         139600000    Japan
Moscow         12593252   Russia
Mexico City    21918936   Mexico
London          9425622  England
New York       20174987  America

In [98]:
# the .index property
city_dataframe.index

Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')

In [99]:
# the .columns property
city_dataframe.columns

Index(['population', 'country'], dtype='object')

In [100]:
# the .keys() method
city_dataframe.keys

<bound method NDFrame.keys of              population  country
Chongquing     31020000    China
Shanghai        2632000    China
Tokyo         139600000    Japan
Moscow         12593252   Russia
Mexico City    21918936   Mexico
London          9425622  England
New York       20174987  America>

### Requirement 6

In [101]:
# Create a Pandas series object named my_pd_series from a collection of
# string keys and collection of numeric values of your choosing

import pandas as pd
my_pd_series = pd.Series([4.56, 1.98, 0.99, 5.50, 7.77],
                         index=['a', 'b', 'c', 'd', 'e'])
my_pd_series

a    4.56
b    1.98
c    0.99
d    5.50
e    7.77
dtype: float64

In [102]:
# modifying a value based on key
my_pd_series['c'] = 0.00
my_pd_series

a    4.56
b    1.98
c    0.00
d    5.50
e    7.77
dtype: float64

In [103]:
# slicing by explicit index
my_pd_series['a':'b']
my_pd_series

a    4.56
b    1.98
c    0.00
d    5.50
e    7.77
dtype: float64

In [104]:
# slicing by implicit integer index
my_pd_series[0:2]

a    4.56
b    1.98
dtype: float64

In [105]:
# masking
my_pd_series[(my_pd_series > 2.98) & (my_pd_series < 5.8)]

a    4.56
d    5.50
dtype: float64

In [106]:
# fancy index
my_pd_series[['d', 'c']]

d    5.5
c    0.0
dtype: float64

In [107]:
my_pd_series.iloc[4]

7.77

### Requirement 7

In [131]:
# Using city_dataframe, demonstrate
# access column via dictionary-style indexing of the column name
population = {'Chongquing': 31020000,
              'Shanghai': 2632000,
              'Tokyo': 139600000,
              'Moscow': 12593252,
              'Mexico City': 21918936,
              'London': 9425622,
              'New York': 20174987}
pop = pd.Series(population)

city_country = {'Chongquing': 'China',
                'Shanghai': 'China',
                'Tokyo': 'Japan',
                'Moscow': 'Russia',
                'Mexico City': 'Mexico',
                'London': 'England',
                'New York': 'America'}
city = pd.Series(city_country)

city_dataframe = pd.DataFrame({'population': pop,
                              'country': city})
city_dataframe


population  country
Chongquing     31020000    China
Shanghai        2632000    China
Tokyo         139600000    Japan
Moscow         12593252   Russia
Mexico City    21918936   Mexico
London          9425622  England
New York       20174987  America

In [132]:
# access column via dictionary-style indexing of the column name
city_dataframe['population']

Chongquing      31020000
Shanghai         2632000
Tokyo          139600000
Moscow          12593252
Mexico City     21918936
London           9425622
New York        20174987
Name: population, dtype: int64

In [133]:
# access column via column names that are strings
city_dataframe.country

Chongquing       China
Shanghai         China
Tokyo            Japan
Moscow          Russia
Mexico City     Mexico
London         England
New York       America
Name: country, dtype: object

In [135]:
# add a new column to the city_dataframe named altitude. Hint: See 
# this example for adding columns

altitude = [29029, 29029, 12388, 18510, 32805, 32100, 41297]
city_dataframe['altitude'] = altitude
city_dataframe

population  country  altitude
Chongquing     31020000    China     29029
Shanghai        2632000    China     29029
Tokyo         139600000    Japan     12388
Moscow         12593252   Russia     18510
Mexico City    21918936   Mexico     32805
London          9425622  England     32100
New York       20174987  America     41297

### Requirement 8

In [114]:
# Create two Pandas series that when added using ‘+’ produce some NaN 
# entries. Use the .add() method and a fill_value to replace the NaN entries.



exp1 = pd.Series([2, 4, 6], index=[12, 8, 66])
exp2 = pd.Series([1, 3, 5], index=[1, 2, 3])
exp1 + exp2

1    NaN
2    NaN
3    NaN
8    NaN
12   NaN
66   NaN
dtype: float64

In [115]:
# .fill()
exp1.add(exp2, fill_value=0)

1     1.0
2     3.0
3     5.0
8     4.0
12    2.0
66    6.0
dtype: float64

### Requirement 9

In [81]:
# Create two Pandas dataframes that when added using ‘+’ produce some 
# NaN entries. Use the .add() method and a fill_value of the mean of one of 
# the dataframes to replace the NaN entries

import pandas as pd
import numpy as np
rng = np.random.RandomState(42)

a = pd.DataFrame(rng.randint(4, 30, (3, 2)),
columns=list('AB'))
a

A   B
0  10  23
1  18  14
2  11  24

In [114]:
b = pd.DataFrame(rng.randint(1, 40, (3, 3)),
                 columns=list('ABC'))
b


A   B   C
0  28  28  20
1  30  11  28
2  25  39  33

In [115]:
# Adding
a + b

A   B   C
0  38  51 NaN
1  48  25 NaN
2  36  63 NaN

In [116]:
# Filling all NaN
a.add(b, fill_value=0)

A   B     C
0  38  51  20.0
1  48  25  28.0
2  36  63  33.0

### Requirement 10

In [118]:
# Create a two-dimensional NumPy array A = rng.randint(5, 10, size=(4, 4))

A = rng.randint(5, 10, size=(4, 4))
A

array([[5, 8, 5, 5],
       [6, 8, 8, 6],
       [7, 5, 9, 5],
       [5, 7, 5, 6]])

In [119]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1,  0,  3,  1],
       [ 2, -3,  4,  0],
       [ 0, -1,  0,  1]])

### Requirement 11

In [120]:
# 4. Create a Pandas dataframe using: df = pd.DataFrame(A, columns=list('QRST')

df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  5  8  5  5
1  6  8  8  6
2  7  5  9  5
3  5  7  5  6

In [121]:
# Demonstrate: subtracting row 1 of df from df using df.iloc[1]

df - df.iloc[1]

Q  R  S  T
0 -1  0 -3 -1
1  0  0  0  0
2  1 -3  1 -1
3 -1 -1 -3  0

### Requirement 12

In [2]:
# Compare and contrast the two sentinel values Pandas uses to represent 
# missing data
import pandas as pd
import numpy as np

In [3]:
values1 = np.array([4, None, 9 , 10])
values1

array([4, None, 9, 10], dtype=object)

In [4]:
values2 = np.array([12, np.nan, 3, 1])
values2

array([12., nan,  3.,  1.])

### Requirement 13

In [5]:
#  Demonstrate the %timeit difference between operations using Python 
# objects and Python integers.

for dtype in ['object', 'int']:
    print("dtype=", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()


dtype= object
51.2 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
1.73 ms ± 83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



### Requirement 14

In [9]:
import pandas as pd
catch_null = pd.Series([99, 1, "Hello There!", None], None)
catch_null.isnull()

0    False
1    False
2    False
3     True
dtype: bool

### Requirement 15

In [46]:
# Create a Pandas dataframe containing null values

null_dataframe = pd.DataFrame([[3,    5,               9],
                              [np.nan, np.nan,    np.nan],
                              [1,      1,      np.nan],
                              [4,      10,           2]])
null_dataframe

0     1    2
0  3.0   5.0  9.0
1  NaN   NaN  NaN
2  1.0   1.0  NaN
3  4.0  10.0  2.0

In [47]:
# drop all rows containing a null value
null_dataframe.dropna()

0     1    2
0  3.0   5.0  9.0
3  4.0  10.0  2.0

In [48]:
# drop all columns containing a null value
null_dataframe.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [49]:
#  drop only rows that contain all null values
null_dataframe.dropna(axis='rows', thresh=3)

0     1    2
0  3.0   5.0  9.0
3  4.0  10.0  2.0

In [51]:
#replacing null with 0
null_dataframe.fillna(0)

0     1    2
0  3.0   5.0  9.0
1  0.0   0.0  0.0
2  1.0   1.0  0.0
3  4.0  10.0  2.0

In [52]:
# forward fill

null_dataframe.fillna(method='ffill')

0     1    2
0  3.0   5.0  9.0
1  3.0   5.0  9.0
2  1.0   1.0  9.0
3  4.0  10.0  2.0

In [53]:
#  backward fill 
null_dataframe.fillna(method='bfill')

0     1    2
0  3.0   5.0  9.0
1  1.0   1.0  2.0
2  1.0   1.0  2.0
3  4.0  10.0  2.0

### Requirement 16

In [48]:
import pandas as pd
import numpy as np

In [49]:
# Demonstrate concatenating two Pandas series

auto = pd.Series(['Transmission', 'Alternator', 'Front Axle'],
                index=[1, 2, 3])

motorcycle = pd.Series(['Frame', 'Front Fork', 'Chain Lubrication'],
                      index=[4, 5, 6])

pd.concat([auto, motorcycle])

1         Transmission
2           Alternator
3           Front Axle
4                Frame
5           Front Fork
6    Chain Lubrication
dtype: object

In [50]:
# Demonstrate concatenating two Pandas dataframe using the .append() 
# method.

ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [51]:
rng = np.random.RandomState(42)

df1 = pd.DataFrame([[3,   5,     9],
                   [6,   11,    31],
                   [1,    21,    23]])

df2 = pd.DataFrame([[13,   15,     99],
                   [16,   11,    77],
                   [10,    21,    3]])


In [52]:
# .append() 
display(df1, df2, df1.append(df2))

0   1   2
0  3   5   9
1  6  11  31
2  1  21  23

0   1   2
0  13  15  99
1  16  11  77
2  10  21   3

0   1   2
0   3   5   9
1   6  11  31
2   1  21  23
0  13  15  99
1  16  11  77
2  10  21   3

### Requirement 17

In [61]:
import pandas as pd
import numpy as np

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [70]:
# Using Pandas dataframes, demonstrate the following joins



dFrame1 = pd.DataFrame({'employee': ['Austin', 'Jose', 'Ellen', 'Laura'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
dFrame2 = pd.DataFrame({'employee': ['Austin', 'Jose', 'Ellen', 'Laura'],
                    'start_date': [2011, 2018, 2013, 1994]})
display('dFrame1', 'dFrame2')




dFrame1
  employee        group
0   Austin   Accounting
1     Jose  Engineering
2    Ellen  Engineering
3    Laura           HR

dFrame2
  employee  start_date
0   Austin        2011
1     Jose        2018
2    Ellen        2013
3    Laura        1994

In [73]:
# one-to-one
df3 = pd.merge(dFrame1, dFrame2)
df3

employee        group  start_date
0   Austin   Accounting        2011
1     Jose  Engineering        2018
2    Ellen  Engineering        2013
3    Laura           HR        1994

In [74]:
# many-to-one
dFrame3 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'dFrame3', 'pd.merge(df3, dFrame3)')

df3
  employee        group  start_date
0   Austin   Accounting        2011
1     Jose  Engineering        2018
2    Ellen  Engineering        2013
3    Laura           HR        1994

dFrame3
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

pd.merge(df3, dFrame3)
  employee        group  start_date supervisor
0   Austin   Accounting        2011      Carly
1     Jose  Engineering        2018      Guido
2    Ellen  Engineering        2013      Guido
3    Laura           HR        1994      Steve

In [76]:
# many-to-many
dFrame4 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('dFrame1', 'dFrame4', 'pd.merge(dFrame1, dFrame4)')

dFrame1
  employee        group
0   Austin   Accounting
1     Jose  Engineering
2    Ellen  Engineering
3    Laura           HR

dFrame4
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

pd.merge(dFrame1, dFrame4)
  employee        group        skills
0   Austin   Accounting          math
1   Austin   Accounting  spreadsheets
2     Jose  Engineering        coding
3     Jose  Engineering         linux
4    Ellen  Engineering        coding
5    Ellen  Engineering         linux
6    Laura           HR  spreadsheets
7    Laura           HR  organization

### Requirement 18

In [84]:
# ON

display('dFrame1', 'dFrame2', "pd.merge(dFrame1, dFrame2, on='employee')")

dFrame1
  employee        group
0   Austin   Accounting
1     Jose  Engineering
2    Ellen  Engineering
3    Laura           HR

dFrame2
  employee  start_date
0   Austin        2011
1     Jose        2018
2    Ellen        2013
3    Laura        1994

pd.merge(dFrame1, dFrame2, on='employee')
  employee        group  start_date
0   Austin   Accounting        2011
1     Jose  Engineering        2018
2    Ellen  Engineering        2013
3    Laura           HR        1994

In [86]:
# left_on and right_on 


dFrame5 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})

display('dFrame1', 'dFrame5', 'pd.merge(dFrame1, dFrame5, left_on="employee", right_on="name")')

dFrame1
  employee        group
0   Austin   Accounting
1     Jose  Engineering
2    Ellen  Engineering
3    Laura           HR

dFrame5
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(dFrame1, dFrame5, left_on="employee", right_on="name")
Empty DataFrame
Columns: [employee, group, name, salary]
Index: []

In [87]:
#  left_index and right_index
dataF1 = dFrame1.set_index('employee')
dataF2 = dFrame2.set_index('employee')
display('dataF1', 'dataF2')

dataF1
                group
employee             
Austin     Accounting
Jose      Engineering
Ellen     Engineering
Laura              HR

dataF2
          start_date
employee            
Austin          2011
Jose            2018
Ellen           2013
Laura           1994

#### Alot of information to take but all very useful, I will definetly look back at this for a refresher. Very vauable information alot of critical thinking and some over thinking the problems in some cases, I have learned alot and will continue to learn.  