### Table of contents

* [Certification](#certification)
* [Import libraries](#import-libraries)
   * [Step 1](#step1)
   * [Step 2](#step2)
   * [Step 3](#step3)
* [Solution](#solution)


### Certification <a class="anchor" id="certification"></a>

I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. -Aaron Rodriguez

### Import libraries <a class="anchor" id="import-libraries"></a>

In [26]:
import numpy as np
from scipy import linalg

3x + 4y + 3z = 10

9x - 10y - 10z = -11

4x + 15y +18z = 37

### Step 1 <a class="anchor" id="step1"></a>

In this code we have changed the the following equation above known as a Linear system to below what is known as a Augmneted Matrix. An Augmented Matrix is used for solving multiple equations such X, Y , and Z. In this case we are solving for 3 equations.

In [42]:
A = np.array([[3,4,3],[9,-10,-10],[4,15,18]])

In [43]:
print(A)

[[  3   4   3]
 [  9 -10 -10]
 [  4  15  18]]


### Step 2 <a class="anchor" id="step2"></a>

 Each number in B represents the total from each column in A 

In [44]:
b = np.array([10,-11,37])

In [45]:
print(B)

[ 10 -11  37]


### Step 3 <a class="anchor" id="step3"></a>

Next we will use what is called the linear-algebra package to solve a linear matrix equation, or system of linear scalar equations. In this case we are solving for x,y,and z of the equation of A by using the .linalg.solve funtion and pluging in A and B. 

In [46]:
xyz = np.linalg.solve(A,b)

In [47]:
print(xyz)

[1. 1. 1.]


To confirm the solution is correct we use (.dot) by computing the A matrix with the solution with the original B matrix if the solution matches the original B matrix then your solution is comfirmed to be correct. 

In [48]:
print(A.dot(xyz))

[ 10. -11.  37.]


### Solution <a class="anchor" id="solution"></a>

X = 1

Y = 1

Z = 1

In [41]:
##The End##