### Table of Contents

* [Certification](#certification)
* [Import Libraries](#import-libraries)
   * [Step 1](#step1)
   * [Step 2](#step2)
   * [Step 3](#step3)
* [Solution](#solution)

### Certification <a class="anchor" id="certification"></a>

I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. -Aaron Rodriguez

### Import Libraries <a class="anchor" id="import-libraries"></a>

In [52]:
import numpy as np
from scipy import linalg

 16v +17w +12x  +66y +45z = 156
 
 29v -18w -15x  +73y +70z = 139
 
-14v +46w -27x  +58y +91z = 154

 33v +37w +24x -123y +54z =  25
 
 20v -27w +18x  +19y -56z = -26

### Step 1 <a class="anchor" id="step1"></a>

In this code we have changed the the following equation above known as a Linear system to below what is known as a Augmneted Matrix. An Augmented Matrix is used for solving multiple equations such V,W,X,Y, and Z. In this case we are solving for 5 equations.

In [64]:
A = np.array([[16,17,12,66,45,],[29,-18,-15,73,70],[-14,46,-27,58,91],[33,37,24,-123,54],[20,-27,18,19,-56]])

In [65]:
print(A)

[[  16   17   12   66   45]
 [  29  -18  -15   73   70]
 [ -14   46  -27   58   91]
 [  33   37   24 -123   54]
 [  20  -27   18   19  -56]]


### Step2 <a class="anchor" id="step2"></a>

 Each number in B represents the total from each column in A 

In [66]:
B = np.array([156,139,154,25,-26])

In [67]:
print(B)

[156 139 154  25 -26]


### Step 3 <a class="anchor" id="step3" ></a>

Next we will use what is called the linear-algebra package to solve a linear matrix equation, or system of linear scalar equations. In this case we are solving for V,W,X,Y,and Z of the equation of A by using the .linalg.solve funtion and pluging in A and B. 

In [68]:
vwxyz = np.linalg.solve(A,B)

In [69]:
print(vwxyz)

[1. 1. 1. 1. 1.]


To confirm the solution is correct we use (.dot) by computing the A matrix with the solution with the original B matrix if the solution matches the original B matrix then your solution is comfirmed to be correct. 

In [70]:
print(A.dot(vwxyz))

[156. 139. 154.  25. -26.]


### Solution <a class="anchor" id="solution"></a>

V = 1

W = 1

X = 1

Y = 1

Z = 1

In [63]:
##TheEnd##